-- AlterTable
ALTER TABLE "Group" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Student" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Teacher" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
